### PR TITLE
Fix curve_rev function likelihood calcs 

### PR DESCRIPTION
**Pull request by arcaldwell49**
The old code incorrectly calculates the likelihood function. It will produce errors if the C.I. contains negative values (this is how I noticed the error). I believe the zscore (starting on line 185) calculation is incorrect for when type = "default"

Minor edits to curve_mean function

### CODE REVIEW

**Comment by arcaldwell49** [comment]
Okay, it appears to be causing an error in the build. Also, a negative `point` value (e.g.., if `measure = "default"` and `point = -2` it will throw an error as well). I think it is caused by line 204 `likelihood <- support * (log(point))`. Is the solution as simple as `likelihood <- support * (point)`

@zadrafi & @avigotsky I am fairly certain all these calcs are correct for odds ratios but can you take another look to see if there are any other errors for means?

**Comment by zadrafi** [comment]
Hi Aaron, thanks for edits on this, I'm still not sure what the error is but whenever I run curve_rev() it doesn't seem to work because the vector is empty which means there's something wrong with the se calculations somewhere. I'll try to take a look over the next few days

**Comment by arcaldwell49** [comment]
Hmm, @zadrafi can you send me a reprex of that error? I am not getting it on my end.

**Comment by arcaldwell49** [comment]
Okay, I see it now. Error is at line 120

`intrvl.limit <- c("lower.limit", "upper.limit")`

**Comment by arcaldwell49** [comment]
Okay, pushing the fix now. I had the wrong logical indicator for setting the se

**Comment by arcaldwell49** [comment]
Also, one more edit that should my resolve the error I was having. @zadrafi please check my likelihood calculation for "default" is correct

`    if ( measure == "ratio") {
    values <- seq(from = df[1, 1], to = df[1, 2], by = 0.01)
    zscore <- sapply(
      values,
      function(j) (log(j / point) / se)
    )
    }

    if (measure == "default") {
      values <- seq(from = df[1, 1], to = df[1, 2], by = 0.01)
      zscore <- sapply(
        values,
        function(j) ((j - point) / se)
      )
    }

    support <- exp((-zscore^2) / 2)
    deviancestat <- (zscore^2)
    if (measure == "ratio"){
    likelihood <- support * (log(point))
    } else {
      likelihood = support * point
    }`

**Pull request merged**
